name: CI Backend
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  rust-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
      - run: cargo check
        working-directory: backend
      - run: cargo clippy -- -D warnings
        working-directory: backend
      - run: cargo test
        working-directory: backend
